### ISSUE TITLE
Elements within the viewport, are not revealing on load.

### ISSUE THREAD

**Issue by greystate** [jlmakes/scrollreveal#105]
I have a page setup with reveals - and I have some objects that are visible right from the start, but they don't animate before I scroll the page, which – I know :) – of course is kinda the idea, but I'd hate to have to recreate the same exact animations that **scrollReveal.js** provides, just because these elements are visible right away, and I can't seem to trigger their reveals after the page has loaded.

Is there some way to do this through the **sr** object? I've tried looking for it in the source, but I haven't had any success in finding a method that seems to do the job...

**Comment by David-van-den-Bor** [comment]
Hi, just giving my 2 cents :-)
I had the same problem (described above by Greystate and others) After reloading a resized browser screen, animated elements were not triggering on INIT. For instance, the H1 headers were missing!

![image](https://cloud.githubusercontent.com/assets/5694412/6541714/8ba0d6f8-c4e0-11e4-89c5-a542d3698170.png)


Here's how I discovered what the problem was: I added the viewport variable to the config vars, like so: 

<code>viewport: document.getElementById('main')</code>

Where "main" was the ID of the HTML element that was visible in the viewport of the small resized screen! And BANG, the elements started to reveal themselves <code>onLoad</code> on small screens (and on mobile) on INIT! 

![image](https://cloud.githubusercontent.com/assets/5694412/6541719/ba867770-c4e0-11e4-9680-cb0d1663daed.png)


The problem wasn't occurring on larger screens, because the HTML container with the ID of "main" was somehow not seen as being in the viewport (for 40%) to be triggered. With responsive design, sometimes the dimension or viewport presence of HTML DOM elements "change" when you resize the viewport. So animations would trigger in one media query, and NOT in another!

Thats why the viewport variable is very handy! It forces ScrollReveal to use specific DOM elements in the viewport as references for objects that HAVE to be in view in order to trigger the animations!

**Comment by greystate** [comment]
Awesome - :+1: for that explanation!

**Comment by drawingfrommemory** [comment]
We had this problem too. We had dynamic content that was being shown/hidden with JS. Calling  `window.sr.init();` after showing/hiding the content (even on load) worked.

Another hack that we had previously was calling window.sr.init(); or scrollTo(0,1) after a settimeout.

    setTimeout(function(){
                    window.scrollTo(0,1);
                  }, 200);

**Comment by David-van-den-Bor** [comment]
What also often "triggers" the script, is to put the initialization inside a <code>$(window).load(function()</code> to <strong>brute force it</strong> to initialize when the page has loaded :-)
<pre><code>
     $(window).load(function() {
      // scrollreveal plugin!
    var config = {
        reset: true,
        move: '50px',
        delay: 'always',
        vFactor: 0.0, // requires 10% of an element be visible to trigger animation.
        easing:   'ease-out',
        scale:    { direction: 'up', power: '0%' },
        // viewport: document.getElementById('main'),
        // viewport: document.getElementsByClassName('container'),
        // viewport: document.getElementsByTagName('p'),
        mobile: true
      }
      window.sr = new scrollReveal( config );
});
</code></pre>

**Comment by makinero** [comment]
@David-van-den-Bor : when I use a $(window).load(function(), elements appears then disappears and appears again with animations. I replaced $(window).load(function() by $(document).ready(function () and it worked as expected. Thank you for the tip !

**Comment by makinero** [comment]
I tested this trick on another website. It does not work ! Animated blocks on this website are taller. I think that scroll reveal waits for the page to display a certain percentage of blocks to animate then it animates them. You can test what I'm talking about on this one : https://wp-themes.com/zerif-lite/ : scroll slowly with a medium window size (mine is 1600px wide), you will see that blocks don't appear immediatly so there's an empy space under each title...

**Comment by RadovanCipovic** [comment]
> We had this problem too. We had dynamic content that was being shown/hidden with JS. Calling `window.sr.init();` after showing/hiding the content (even on load) worked.
> 
> Another hack that we had previously was calling window.sr.init(); or scrollTo(0,1) after a settimeout.
> 
> ```
> setTimeout(function(){
>                 window.scrollTo(0,1);
>               }, 200);
> ```

after spending around 6h researching how to fix this thing, that not showing elements with scrollReveal. Eaven i know its long time ago that replied, i just want to say a big THANK YOU! have a good night !
