### ISSUE TITLE
Reveal not working on refresh

### ISSUE THREAD

**Issue by Koroeskohr** [jlmakes/scrollreveal#17]
Hello there,
I'm having trouble using this rather simple-to-use library : the revealing only appeared once on first load, then didn't show up at all. Here's what I used : http://koroeskohr.github.io/scrollRevealTests/tests/scrollReveal/

Maybe I'm just blind, I'd like some help! 
Awesome work, keep it up!

**Comment by mattrothenberg** [comment]
Hey, @jlmakes!

Any news on this one? I'm experiencing some serious weirdness when using scrollReveal with a custom Wordpress theme (https://github.com/roots/sage). 

I'm using Gulp to serve a preview of my website / build assets, and it seems that anytime I modify the original scrollReveal function invocation (e.g., passing a configuration object to the function below), I have to rebuild the entire Javascript pipeline via Gulp to get the new changes to work. Until I rebuild, I get a ```scrollReveal is not defined``` error in the console.
```
window.sr = new scrollReveal();
```

**Comment by jlmakes** [comment]
This is a legacy issue. ScrollReveal no longer auto-instantiates.

Your issue is unrelated @mattrothenberg —but from what you’ve described, this sounds like an issue with the Gulp configuration… not a bug with ScrollReveal. I would recommend opening an issue on the theme’s repository, the theme author should be able to help you.
