### ISSUE TITLE
Using ScrollReveal with Angular

### ISSUE THREAD

**Issue by pavlos-io** [jlmakes/scrollreveal#20]
So, I have been trying to use the script along with angular. The partials(views) that get called in the "ng-view" div, can't animate,because the app has already been bootstraped.

I have tried several things to make js code run after a view is called, and it executes, but the ScrollReveal code doesn't. Is there some kind of conflict if it's used in a partial file?

Thank you.

**Comment by marko911** [comment]
@orapouso I used your fox script but I get a console error saying ScrollReveal isnt a constructor, I followed tthe instructions on the script install page exactly. Added both scroll-reveal-container and data-sr-container, both give me same error

**Comment by jlmakes** [comment]
@marko911 Thanks for searching past issues.

I took a look at the @orapouso’s repo, and it looks like on [line 11](https://github.com/orapouso/fox-angular-scrollReveal.js/blob/master/src/fox-angular-scrollReveal.js#L11) there’s this block:

```js
if (!this.scrollReveal) {
    this.scrollReveal = new ScrollReveal(defaultOpts);
    $scope.$emit('scrollReveal.created');
}
```

Since his plug-in uses version 2 of ScrollReveal, the constructor should not have a capitalized S.

```diff
    if (!this.scrollReveal) {
-       this.scrollReveal = new ScrollReveal(defaultOpts);
+       this.scrollReveal = new scrollReveal(defaultOpts);
        $scope.$emit('scrollReveal.created');
    }
```

I would attempt to make this change to see if it fixes the problem @marko911 :bow:

**Comment by jlmakes** [comment]
The directive requires `window.scrollReveal` be defined, which sounds like it isn’t for you @marko911. I would make sure you are using version 2 of ScrollReveal, and that it is loaded on your page _before_ Angular and this directive.

**Comment by marko911** [comment]
@jlmakes I tried that and I get another error saying scrollReveal is not defined for that

**Comment by marko911** [comment]
Where can I find v 2 of scrollreveal? @jlmakes

**Comment by marko911** [comment]
@jlmakes or is there a way of using the newest version of scrollReveal with angular?

**Comment by jlmakes** [comment]
@marko911 you can always looked for past releases in branches and tags dropdown:

![branches-tags](https://cloud.githubusercontent.com/assets/2044842/14282662/a942d828-fb3f-11e5-924c-47898bbfde6d.gif)

You can also find the [version 2 documentation here in the WIKI](https://github.com/jlmakes/scrollreveal.js/wiki)

**Comment by marko911** [comment]
@jlmakes thanks for all your help so far appreciate it...I'll try to troubleshoot etc. Any hint as to why my reveal items dont show when I scroll down ?

**Comment by jlmakes** [comment]
@marko911 If things aren’t revealing, it’s typically because the elements aren’t considered visible.

>"...or is there a way of using the newest version of scrollReveal with angular?"

Actually yes… I just got it working locally.

1. Follow the install instructions in the README, specifically reference [Section 4.2.](https://github.com/jlmakes/scrollreveal.js#42-improve-user-experience) for best results.

2. Inside your Angular application, ensure that the appropriate class names are on your elements.

3. Inside your view controller, inject $scope and use the `sr.reveal()` as you normally would:

```js
(function () {
    "use strict";

    angular.module("myApp").controller("ViewCtrl", ViewCtrl);

    function ViewCtrl($scope) {
        $scope.$on("$viewContentLoaded", function () {
            sr.reveal('.js-reveal');
        });
    }
})();
```

**Comment by marko911** [comment]
I did everything to the tee, didnt get any errors but my reveal elements are all hidden, none are showing when I load the page.  I injected this into the index.html : 
`  <script>
    window.sr = ScrollReveal();

    // Add class to <html> if ScrollReveal is supported
    if (sr.isSupported()) {
        document.documentElement.classList.add('sr');
    }
    </script>
    <style>
    
    .sr .media-entry {
        visibility: hidden;
    }
    </style>`

and at the bottom of the partial that uses the reveal I appended  :  
`<script>
sr.reveal('.media-entry', {
    container: '.media-list'
});
</script>`

and I added the code you just posted into my controller as well.

**Comment by jlmakes** [comment]
type `sr.store.elements` into the console, and explore your elements… do they all have `seen: false` ?

**Comment by marko911** [comment]
Yes, I only have 1 object returned and its seen: false.

**Comment by orapouso** [comment]
I would love to help but scrollReveal changed too much from version 2 to 3 for me to take a look right now. I managed to get my plunkr example to work with 3.1.4, but the `"enter left and move 50px over 1s"` language is not working anymore.

I don't know if this is the right place to ask this @jlmakes, but the way it looks right now, it is impossible to randomize the parameters for every element inside a container, right? Since you need to **reveal a selector** with individual parameters, there is no way you can do it with individual elements, unless you would put an unique id/class in each element.

That would not be the case if `.reveal(selector)` would also accept an element or an element list in addition to the selector. That way you could reveal individual elements. Is that possible/manageable/desirable?

**Comment by jlmakes** [comment]
@orapouso the reveal method accepts DOM nodes as well as selectors.

**Comment by marko911** [comment]
@jlmakes I fixed it, I realized you must use .sr.[classname] in the reveal script thats inserted at the bottom of the page, problem is, there are no reveal animations now.

**Comment by orapouso** [comment]
@jlmakes my bad. I tried `.reveal()` with __nodeList__ and the error was that it was not a valid selector so I assumed individual nodes would not work also.

**Comment by jlmakes** [comment]
@marko911 Using ScrollReveal within Angular has been solved, please open a new issue with your problem.

**Comment by liganggang** [comment]
is there a requirement for the angularjs version? 
according to documentation, failed!
