### ISSUE TITLE
Different viewFactor on content with images or only text

### ISSUE THREAD

**Issue by Dani79** [jlmakes/scrollreveal#312]
Hi,

I'm having some trouble with this nice script. Here is my "Demo page": http://www.sausundbraus.info/de/blog.html

I have a "first box with image on top". The "first box" starts earlier than the "search box".
The "second box" with h2 headline, has a smaller viewfactor as the "first box".

What am I doing wrong?
Thank you

**Comment by jlmakes** [comment]
I see the demo, but I don't understand what should be happening.
Can you describe to me what are you trying to do here?

**Comment by Dani79** [comment]
Hey, ok resize the browser to the "first box" from bottom to top. Now you can see both boxes start NOT at the same time!? Div with images start earlier?!

Daniel

**Comment by jlmakes** [comment]
I think it's an illusion because your design is predominantly white, and you have a large dark image animating.

Both of these elements reveal at the same time...
but notice how the darker box appears to happen sooner:

![sr_timing_illusion](https://cloud.githubusercontent.com/assets/2044842/19836415/83d94e46-9ea0-11e6-8c7b-21779429219a.gif)

The gif compression might make it even more dramatic, but you can see a [Live Example](http://jsbin.com/wawinas/edit?html,css,js,output). Also, you might want to try not using `scale` in your animations, because it makes larger elements appear even more dramatic (since they move a lot more than smaller elements).

**Comment by Dani79** [comment]
Hi, hmm look at my gifs, than you see the effect better :)

http://www.sausundbraus.info/reveal.gif <--- different DIV height.
http://www.sausundbraus.info/reveal2.gif <--- same DIV height

Daniel

**Comment by jlmakes** [comment]
Yes! Thank you for the gifs Daniel, very helpful. Let's break this down.

The default `config.viewFactor` is `0.2`, meaning 20% of an element has to be in view for ScrollReveal's to reveal or reset the element. So if you have different height elements, that threshold will be at different places.

![screen shot 2016-10-30 at 2 48 36 pm](https://cloud.githubusercontent.com/assets/2044842/19836967/f9e17b2c-9eaf-11e6-92e8-64f2fee7242c.png)

This is why your elements aren't revealing/hiding at the same time, even though the elements top edge are in line with each other. You're not doing anything wrong.

**Comment by Dani79** [comment]
Hey, ah ok, i understand! And what can i do that show/hide to the same time? px instead of % ?

Thank you!

**Comment by jlmakes** [comment]
If you want them to reveal at the same time, the only way to do this is to use `config.viewFactor = 0`. There is no notion of static distances like `px` currently.

**Comment by Dani79** [comment]
Ok, i try this! Thank you Julian.

**Comment by jlmakes** [comment]
Another idea, is to use `viewOffset` which is a similar idea, but instead of changing the edges of the element, it changes the edges of the viewport... and it _does_ use pixels.

_Example:_
![viewoffset](https://cloud.githubusercontent.com/assets/2044842/19837064/35a1ac52-9eb2-11e6-9757-5b130f5e85f4.png)

So you might want to explore something like this:
```js
sr.reveal('.selector', {
  viewFactor: 0,
  viewOffset: {
    top: 25,
    right: 25,
    bottom: 25,
    left: 25,
  },
});
```

**Comment by Dani79** [comment]
Hi, ok thats perfect! Thank you!!

Daniel
