### ISSUE TITLE
Resize element issue

### ISSUE THREAD

**Issue by jcfg123** [jlmakes/scrollreveal#313]
First off, amazing project, really well done!

I am having a slight problem when it comes to resized elements. I have some pictures which I have previously revealed, but the problem is that after resizing the pictures, they still remain the same width/height on reveal.

This is a portion of my code:

```js
document.addEventListener('DOMContentLoaded', function () {
  var pictures = ($('.rpic'));
  for (var a = 0; a < pictures.size(); a++){
    (pictures.get(a)).style.width = (window.innerWidth - 25)/3 + 'px';
    (pictures.get(a)).style.height = (window.innerWidth - 25)/3 + 'px';
  }
  //Just to initialize the height/width
  sr.reveal('.rpic');
  
  
  $(window).resize(function(){
    var pictures = ($('.rpic'));
    for(var a = 0; a < pictures.size(); a++){
      (pictures.get(a)).style.width = (window.innerWidth - 25)/3 + 'px';
      (pictures.get(a)).style.height = (window.innerWidth - 25)/3 + 'px';
    }
    //Adjust the height/width when resized
  });
});
```
Thanks for any advice in advance!

**Comment by jlmakes** [comment]
ScrollReveal takes a snapshot of the `style` attribute when you first call `sr.reveal()` so that it can preserve whatever inline styles were already present... but you are changing the `style` attribute after ScrollReveal takes this snapshot, which is why ScrollReveal overwrites your changes inside the `resize` handler with whatever it has stored.

Instead I recommend...

### Use CSS to Control Element Width (Not JavaScript)

Sometimes JavaScript is a better choice, but this really looks like a job for CSS and the [calc property](https://developer.mozilla.org/en-US/docs/Web/CSS/calc).

_example:_

```css
.rpic {
  width: calc((100% - 25px) / 3);
}
```

It's simpler, has [good support](http://caniuse.com/#search=calc) and circumvents your JavaScript conflicting with ScrollReveal.

**Comment by jcfg123** [comment]
Thanks for the help! Do you have any advice on how to handle changing the height of the elements with respect to the width in css? I tried changing the css property of the pictures through javascript and the width through your method in CSS (which works great!) but I can't get the height to work...

**Comment by jlmakes** [comment]
Images try to maintain their aspect ratio, so you shouldn't have to worry about height...
assuming these images are square to begin with.

If you change the width of a 25 x 25 px image to 200px, the height will be come 200px. [See Demo](http://jsbin.com/yuwujun/edit?html,css,output)

**Comment by jcfg123** [comment]
Ok sounds good! Thank you so much for all your help!
