### ISSUE TITLE
Using scrollReveal with fullpage.js

### ISSUE THREAD

**Issue by brianecook88** [jlmakes/scrollreveal#321]
I'm trying to use this plugin with fullpage.js, to show section content as the fullpage layout scrolls between sections. The issue is that fullpage.js disables scrolling and uses it's own javascript to scroll between sections. Ideally I'd like to call the reveal() function on the elements within the section being shown. I've tried this without any success: 

First I set up the instance:

```js
var config = {
      duration: 1000,
      origin: 'left',
      reset: false,
      distance: '100px',
      viewport: document.getElementById('fullpage')
    };

window.sr = new ScrollReveal( config );
```

Then the call reveal() in the fullpage callback

```js
$('#fullpage').fullpage({
        menu: '.page-nav__list',
        fixedElements: '.site-header, .page-nav',
        css3: true,
        onLeave: function(index, nextIndex, direction) {
          sr.reveal('.reveal-left').init();
        }
});
```

Nothing is happening. I've been using this ticket for reference: https://github.com/jlmakes/scrollreveal/issues/42

Is there anyway to use ScrollReveal on non-scrolling events? The issue is that fullPage.js disables scrolling and just makes a long fixed element with all the sections inside, then uses it's own JS to scroll between sections? Thanks in advance.

**Comment by jlmakes** [comment]
Hey @brianecook88,

First up, I presume you're using v3, but you're using an unsupported v2 option `config.viewport`—this has been renamed `config.container`. So in actuality, your current configuration is using the default container: the `<html>` element.

Secondly, you've described pretty well what the problem is: ScrollReveal requires native scrolling to not only trigger animation, but also to evaluate element visibility. This has come up quite a few times, and it seems to come down to this...

Since you won't be using scrolling or require checking element visibility, it's probably less work to simply make the CSS yourself.

Perhaps a disappointing answer, but ScrollReveal only generates a small amount of CSS. The majority of the library is the scroll handling and figuring out what and when to reveal. In your case, you don't need scroll handling and you know exactly what will be visible and when.

>Fullpage.js adds multiple classes in different elements to keep a record of the status of the site:
> `active` is added the current visible section and slide.

So for example:

```css
#fullpage .reveal {
	transform: translateX(-100px);
	opacity: 0;
	transition: opacity 1s, transform 1s;
}

#fullpage .active .reveal {
	transform: translateX(0);
	opacity: 1;
}
```

Simply add `.reveal` to all the elements you wish to reveal.

Hopefully this helps point you in the right direction.

**Comment by brianecook88** [comment]
👍  Very thorough response, much appreciated.
