### ISSUE TITLE
Confused with async method

### ISSUE THREAD

**Issue by ekfuhrmann** [jlmakes/scrollreveal#334]
First I'd like to thank you for the amount of time and effort you've put into this library. It's been fantastic utilizing it on my sites and the work you put into it doesn't go unnoticed.

Now on to my issue...

I'm using the async method from the documentation (below) for my site:

```html
<!-- index.html -->
<div id="fooContainer">
  <div class="foo">foo</div>
  <div class="foo">foo</div>
  <div class="foo">foo</div>
</div>

<!-- ajax.html -->
<div class="foo">foo async</div>
<div class="foo">foo async</div>
<div class="foo">foo async</div>
```

```js
var fooContainer, content, sr, xmlhttp;

fooContainer = document.getElementById('fooContainer');

sr = ScrollReveal();
sr.reveal('.foo', { container: fooContainer });

// Setup a new asynchronous request...
xmlhttp = new XMLHttpRequest();
xmlhttp.onreadystatechange = function() {
  if (xmlhttp.readyState == XMLHttpRequest.DONE) {
    if (xmlhttp.status == 200) {

      // Turn our response into HTML...
      var content = document.createElement('div');
      content.innerHTML = xmlhttp.responseText;
      content = content.childNodes;

      // Add each element to the DOM...
      for (var i = 0; i < content.length; i++) {
        fooContainer.appendChild(content[ i ]);
      };

      // Finally!
      sr.sync();
    }
  }
}

xmlhttp.open('GET', 'ajax.html', true);
xmlhttp.send();
```

My question specifically is in regards to the line `xmlhttp.open('GET', 'ajax.html', true);`.

I'm using SR on multiple pages and was wondering if there is any way to specify a collection of pages?

**Comment by jlmakes** [comment]
Thanks @ekfuhrmann 

My understanding is that you’re asking about more complex ways to use `XMLHttpRequest` (i.e. fetching HTML content from multiple pages). Can you better explain what problem you’re having?

**Comment by ekfuhrmann** [comment]
This is probably more of me just not being great at JS yet. Anyway I included that async function into my site in order to allow for me to stagger loading multiple elements that share a class. For example using your example code, I have multiple `<div class="foo">foo async</div>` elements across a page that I wan't to load when they come into viewport. Everything works fine on my end; however I see a console error that it can't find `ajax.html` since I don't have that file on my site.

If I outright remove `xmlhttp.open('GET', 'ajax.html', true);`, the animations all load at once when page loads.

How can I just have it async load like it is, without having it toss out an error for the ajax.html. I know I can create a blank `ajax.html` and then the errors go away, but I can't help but feel like I'm missing something more.

**Comment by jlmakes** [comment]
I’m getting the feeling that you have misunderstood the purpose of the code example you are referencing (and trying to use). Let me revise it a little, and recap using different words, to see if it helps move the conversation forward:

### Asynchronously Loading Content

We have our basic page, `index.html`:

```html
<div id="fooContainer">

	<div class="foo">1</div>
	<div class="foo">2</div>
	<div class="foo">3</div>
	<!-- ...

	the page has already loaded, but
	we want to add more `div.foo`
	elements.
	
	-->
  		
</div>
```

Let’s say our extra elements live on another page `ajax.html` like this:

```html
<div class="foo">4</div>
<div class="foo">5</div>
<div class="foo">6</div>
```

We turn to the built-in Web API method [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), to make an "asynchronous request" for our extra content. The basic usage looks like this:

```js
var request = new XMLHttpRequest()

/**
 * This method is called when the
 * progress of our request updates.
 */
request.onreadystatechange = function () {

	/**
	 * Inside here we place all of the logic to check
	 * the current status, and handle the success or
	 * failure of the request.
	 */
}

request.open(
	'GET',		// method
	'ajax.html',	// url
	true		// asyncronous
)

request.send()
```

When the completed JavaScript runs, we expect our DOM to look like this:

```html
<div id="fooContainer">

	<div class="foo">1</div>
	<div class="foo">2</div>
	<div class="foo">3</div>
	<div class="foo">4</div>
	<div class="foo">5</div>
	<div class="foo">6</div>
  		
</div>
```

Let’s fill in the `request` object to make this happen.



```js
var request = new XMLHttpRequest()

request.onreadystatechange = function () {

	 /**
	 * If our request is complete and succesful
	 */
	if (xmlhttp.readyState === XMLHttpRequest.DONE) {
		if (xmlhttp.status === 200) {

			/**
			 * We create a DIV, and assign the response
			 * to its innerHTML property. This conveniently
			 * turns our string of html into a DOM fragment.
			 */
			var div = document.createElement('div')
			var response = xmlhttp.responseText
			
			div.innerHTML = response

			/**
			 * But we don’t want our DOM fragment wrapped
			 * in a div element, we just used it to build
			 * the fragment... so we extract the child node
			 * list, and convert it to an array.
			 */
			var content = Array.prototype.slice.call(div.childNodes)

			/**
			 * For simplicity here, we hard code the destination.
			 */
			var target = document.getElementById('fooContainer')

			/**
			 * Now we can freely map over the content,
			 * and append each node to the document.
			 */
			content.map(function (node) {
				target.appendChild(node)
			})
		}
	}
}

request.open('GET', 'ajax.html', true)
request.send()
```

As you can see, nothing about what we’ve covered so far includes ScrollReveal. If your question is about anything that’s going on up until this point... I can’t offer much help beyond what I’ve detailed above.

### Adding ScrollReveal

Now if we were to decide that all `.foo` elements should reveal on scroll, we add this JavaScript:

```js
window.sr = new ScrollReveal()

sr.reveal('.foo', { container: '#fooContainer' })
```

The problem is that when our page loads, it only has 3 matching elements in the DOM. This means `sr.reveal()` will only setup reveal animations for `.foo` element 1, 2 and 3, and the asynchronously loaded 4, 5 and 6 will have none.

How do we fix this problem?

Well we could just call `reveal()` again after we load the new content. That works... but we used a custom configuration, so we’d need to also pass the same configuration object down into the async request handler. Already getting messy.

To make this situation nicer, ScrollReveal stores all `reveal()` calls and their arguments. We can recall all past reveals (in order, with the correct options) by simply invoking `sr.sync()`... this effectively re-configures all animations, which since our DOM has changed, means that our updated reveal will include the newly loaded `.foo` elements (4, 5 and 6).

*The finished JavaScript:*

```js
window.sr = new ScrollReveal()
sr.reveal('.foo', { container: '#fooContainer' })

var request = new XMLHttpRequest()

request.onreadystatechange = function () {

	if (xmlhttp.readyState === XMLHttpRequest.DONE) {
		if (xmlhttp.status === 200) {

			var div = document.createElement('div')
			var response = xmlhttp.responseText
			
			div.innerHTML = response

			var content = Array.prototype.slice.call(div.childNodes)
			var target = document.getElementById('fooContainer')

			content.map(function (node) {
				target.appendChild(node)
			})

			if (sr !== undefined) sr.sync()
		}
	}
}

request.open('GET', 'ajax.html', true)
request.send()
```

So you can see, the majority of this code (and example) has nothing to do with ScrollReveal... it’s simply a demonstration of where `sr.sync()` can be really helpful. Hopefully this helps.

I’ll make sure to revisit this section in the new documentation.

**Comment by ekfuhrmann** [comment]
Well after going back and reviewing my code, I clearly was wrong that the aforementioned code block we are discussing was causing my content to work properly. I think I did it in tandem with creating SR specific classes that I apply individually to each block I want to animate, and then attributed it to the async function, rather than realizing that just having individual classes with no delay timer allowed for each element to load when coming into Viewport.

Nonetheless it's clearly not an issue with your code by any means and was more a lack of understanding on my end. Thank you for taking the time to explain it better to me!
