### ISSUE TITLE
[Violation] Forced reflow while executing JavaScript took 42ms

### ISSUE THREAD

**Issue by RusinovAnton** [jlmakes/scrollreveal#335]
- MacOS
- Google Chrome, Version 57.0.2987.133 (64-bit)
- 3.3.4
Actual code:
```js
;(function ($) {
  var options = {};
  window.sr = ScrollReveal(options);

  sr.reveal('.sr-item', { viewFactor: 0.6, duration: 500 });
  sr.reveal('.sr-item--seq', { viewFactor: 0.6, duration: 500 }, 50);
})(jQuery);
```

Hello. Today I've noticed a warning in the console on my site that I use scrollReveal on:  
```
[Violation] Forced reflow while executing JavaScript took 42ms
```
So I took timeline snapshot and saw this.

![screen shot 2017-04-05 at 10 23 52 pm](https://cloud.githubusercontent.com/assets/13165540/24723316/d1c023a2-1a4f-11e7-83b7-f7c767d8a583.jpg)

So the question is there any possible way I can improve perfomance? Thank you

**Comment by jlmakes** [comment]
ScrollReveal relies on `getComputedStyle()` and editing style attributes (modifying the DOM). They are used together in the same loop, which causes some layout thrashing.

The development branch (`v4.0.0-beta.3` currently) attempts to batch things, so that all computed styles are gathered before any DOM modifications. I can’t guarantee a performance boost yet, but if you'd like to give it a try, it may help to improve this for the next release.

**Comment by RusinovAnton** [comment]
@jlmakes, thanks for your response, I think I'll try to upgrade it this weekend.

**Comment by AndrewEastwood** [comment]
@RusinovAnton did it help?

**Comment by RusinovAnton** [comment]
@AndrewEastwood yup it did, actually you can see how it works on prod [here](http://orbirect.com/).

**Comment by AndrewEastwood** [comment]
awesome!

**Comment by FilhoSergio** [comment]
Nice .

**Comment by frankyphilip** [comment]
Can you tell me why does this violation come?
