### ISSUE TITLE
Only the half of the elements to be seen are shown.

### ISSUE THREAD

**Issue by AbrahamHalil** [jlmakes/scrollreveal#352]
Hi,

Today I ran into a problem. Only the half of the elements to be seen are shown (screenshot below).
I have to resize the browser vertically, then come the the other elements.

Any Ideas?
Best Regards

I am using `https://unpkg.com/scrollreveal@4.0.0-beta.5`

```js
window.sr = ScrollReveal({ 
    distance: '200px',
    duration: 600,
    delay: 150,
    opacity: 0.01,
    scale: 0.11,
    easing: 'ease-out',
    useDelay: 'onload',
    viewFactor: 0.11,
    viewOffset: { top: 48, right: 0, bottom: 0, left: 0 },
 });

sr.reveal('.move', 150);
```

![bug-sr](https://user-images.githubusercontent.com/19261428/27217833-d0554c22-527b-11e7-85a3-bd704cdb9b03.jpg)

**Comment by jlmakes** [comment]
Without a live demo, I can't effectively troubleshoot this.

In general, both **scroll** and **resize** event handlers check if elements are visible, and animate the ones that are. The difference is that **resize** first checks the size of elements, since that may changed during resize.

If you inspect the `sr.store.elements` object in the console, you can see all the information ScrollReveal has about each of your elements.

![screen shot 2017-06-16 at 2 57 51 pm](https://user-images.githubusercontent.com/2044842/27227559-39a4d8a0-52a4-11e7-9e9d-4dcb8ff50107.jpg)

I recommend looking at the `geometry` property when your page loads, and _after_ you resize the page. You can compare the `visible` property with common sense, to see if elements are correctly evaluated. Etc.

In general, if you have a problem, I recommend trying to understand what the store data looks like—especially if you can‘t provide a working demo of the problem. However, creating a [JSBin](https://jsbin.com) that demonstrates the issue is the best way to receive support.

**Comment by cobblehillmachine** [comment]
I am seeing a similar issue (you can actually view it [here](http://cobblehill2016.cobblehilldigital.com/services/) , and it appears that the elements are not "visible" when they should be, which is odd because elements with the same styles _are_ being revealed. @vicula

**Comment by jlmakes** [comment]
Well this seems to be an issue on both v3 and v4, but it’s not something I’ve encountered before. After a look around the site (thanks for the live demo @Vicula) I don’t see what’s wrong.

I’ve [modified v3](https://gist.github.com/jlmakes/882d8342e69b79603e6566cbc6585731#file-scrollreveal-debug-js-L730) for you @Vicula with a public `isElementVisible()` method that dumps its internal data.

If there’s something wrong, I think it should show up there. If you don't mind, can you swap your version of ScrollReveal with this debug copy and let me know when it’s live—I’ll then look through and debug again!

**Comment by cobblehillmachine** [comment]
I switched out my version for the debug version. I ran some of the Li's with `isElemVisible()` and found that some of the elements that are being passed to `_getOffset` are undefined. I left the debug live so you can still go and look through it. @jlmakes 
![screen shot 2017-06-23 at 10 06 50 am](https://user-images.githubusercontent.com/3064548/27485815-430ed302-57fc-11e7-99f4-9b4128e4d114.png)

**Comment by jlmakes** [comment]
@cobblehillmachine I believe I have found the issue.

This line at the bottom of `confirmBounds()` inside `isElemVisible()` seems a little off...

```js
return top < viewBottom &&
    bottom > viewTop &&
    left > viewLeft && // this compares left to left?
    right < viewRight // this compares right to right?
```

Looking at this logic, and the output numbers, I believe it should operate like this

```js
return top < viewBottom &&
    bottom > viewTop &&
    left < viewRight &&
    right > viewLeft
```

This follows the same convention, and in my tests, fixes the issue.

**Comment by cobblehillmachine** [comment]
I can confirm that @jlmakes 's solution fixed my problem. Thanks for the speedy response and all your help.

**Comment by jlmakes** [comment]
@cobblehillmachine I just patched to `v3.3.6` which includes this fix.

_Available at:_
`https://unpkg.com/scrollreveal@3.3.6`

@AbrahamHalil If you are still having this issue, can you please open a new issue with a live demonstration of the problem so it can be debugged? If a similar bug is also happening in v4, I would love to get this squashed.

**Comment by cobblehillmachine** [comment]
@jlmakes You left a console.log on line 172.

**Comment by jlmakes** [comment]
That was not added or left there by mistake recently. That is by design in version 3—it warns you when `reveal()` is called with a selector that matches no elements.

In version 4, there is a [debug flag to enabled/disable log messages](https://github.com/jlmakes/scrollreveal/issues/351).
