### ISSUE TITLE
1px white space between elements

### ISSUE THREAD

**Issue by relish27** [jlmakes/scrollreveal#355]
* Windows 10
* Firefox
* ScrollReveal v3.3.4

I have three divs side-by-side.  Using Bootstrap grid columns, so each are taking up 1/3 of the parent container.  With the SR class on each of them, they do do the scroll reveal animation.  However, there's a 1px space between two of them.  If I remove the SR class, this 1px goes away.

![screenshot-localhost 7883-2017-06-21-14-19-58](https://user-images.githubusercontent.com/534728/27402602-c46413fc-568c-11e7-89c4-40b5b858fb0a.png)

```html
<section id="home-main-features">
    <div class="container">
        <div class="row">

            <div class="col-sm-4 col-md-4 main-feature scroll-reveal">
                <a href="#">
                    <div class="feature-content">
                    <h2>See Design Trends</h2>
                        <p class="default-hidden">
                        What’s new in tile? See the latest styles and materials. 
                        </p>
                        <div class="arrow-white"></div>
                    </div>
                    <div class="overlay"></div>
                    <img src="images/home-feature1.jpg" alt="" />
                </a>
            </div>

            <div class="col-sm-4 col-md-4 main-feature scroll-reveal">
                <a href="#">
                    <div class="feature-content">
                    <h2>Visit a Showroom</h2>
                        <p class="default-hidden">
                        See our tile selection in person. Get support from a Kate-Lo design consultant. 
                        </p>
                        <div class="arrow-white"></div>
                    </div>
                    <div class="overlay"></div>
                    <img src="images/home-feature2.jpg" alt="" />
                </a>
            </div>

            <div class="col-sm-4 col-md-4 main-feature scroll-reveal bottom-stack">
                <a href="#">
                    <div class="feature-content">
                    <h2>Find Tile Resources</h2>
                        <p class="default-hidden">
                        Get free guides and locate tile installers and retail stores that carry Kate-Lo tiles.
                        </p>
                        <div class="arrow-white"></div>
                    </div>                 
                    <div class="overlay"></div>       
                    <img src="images/home-feature3.jpg" alt="" />
                </a>
            </div>

        </div> <!-- .row -->
    </div> <!-- .container -->
</section> 
```

```js
window.sr = ScrollReveal({ 
	reset: true,
	duration: 1000, 
	distance: '40px',
	scale: 1,
	easing: 'cubic-bezier(0.3, 0.2, 0.1, 1)',

});
sr.reveal('.scroll-reveal');
```

Thanks!

**Comment by jlmakes** [comment]
This is caused by a rounding error.

The class `col-x-4` uses `width: 33.3333333%`, which has created `1px` gaps like this in the past... but browsers have gotten smarter in recent years so this doesn’t seem to be an issue much anymore.

However, in Firefox when using `transform: translate` in combination with repeating decimal widths, this rounding error can still occur. (I tested this and confirmed Chrome does not have this issue.)

[Reproduction](http://jsbin.com/hisiheh/edit?html,css,output) _(must use Firefox, and only is visible at certain widths)_

The solution I would suggest is to install ScrollReveal v4 (currently in a stable late stage beta), because it will remove the styles generated by ScrollReveal after reveal animations complete—avoiding this bug.

`https://unpkg.com/scrollreveal@4.0.0-beta.9` or `npm install scrollreveal@beta`

It is 99% backwards compatible, but pease take a look at [what’s new](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md).

The only caveat is that you cannot use `options.reset = true`, as this causes reveal animations to play repeatedly and prevents ScrollReveal from removing the generated styles.

**Comment by relish27** [comment]
Thank you for the quick response!  I had wondered if the 33.333% could be causing the problem, too.

I appreciate the option to try the v4 beta version.  I'm a little hesitant, though, because I'd prefer to use the reset=true.  Maybe I'll find a way to make this work with whole numbers (33 + 33 + 34) .  Will v4 do away with the reset=true completely?

**Comment by jlmakes** [comment]
>"Will v4 do away with the reset=true completely?"

Sorry, I wasn’t clear. `options.reset` has not been removed in v4.

Here is the relevant excerpt from the change log:

>"ScrollReveal removes generated styles after reveals complete when `options.reset` is false."

Basically, when ScrollReveal no longer needs styles, it will remove them... but in the case of `options.reset = true`, those styles are always needed, and thus are never removed.

I suggested upgrading to v4 because it would remove the conflicting styles (as shown in the live test I linked before), as long as you weren't using `reset: true`, but I see now that the reset option in this situation is important to you.

>"Maybe I'll find a way to make this work with whole numbers (33 + 33 + 34)"

That could work!

If you’re open to changing your CSS, I would recommend looking into [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/). It should allow you to easily create a 3-column layout, and there’s a good chance it won't have the rounding error associated with using floats and repeating decimal percentages.

**Comment by relish27** [comment]
Just was trying this with 33+33+34, but realized the obvious problem now is that the one at 34% is taller than the other two.  :\  Obvious now.  

I just tried using your v4 beta in my local example... and even with reset = true it works....

Good thought on using flexbox if needed.

**Comment by lclghst** [comment]
My 2c:

You can pick up the [alpha release](https://v4-alpha.getbootstrap.com/) of Bootstrap, which has moved to Flexbox
Or maybe you could use css calc and override the 33.3333% with calc(100% / 3)

Not sure if it will work for you, depending on what browsers you need to support etc
