### ISSUE TITLE
Only first element in viewport reveals

### ISSUE THREAD

**Issue by skube** [jlmakes/scrollreveal#361]
I'm not sure what I'm doing wrong but I can only get the **first** element to reveal. I'm not seeing any errors. I'm using Web Starter Kit as starting point.

I'm activating by:

```js
window.sr = ScrollReveal();
sr.reveal('.mydiv');
sr.reveal('.anotherdiv');
```

Also, it **does not** reveal on scrolling back up or resizing the window.

My specs:
MacOS 10.12.5
Chrome 59.0.3071 & Firefox 54.0.1
ScrollReveal 3.3.6

**Comment by jlmakes** [comment]
Can you recreate the issue using [JSBin](https://jsbin.com) or provide a link to your live project?

**Comment by jlmakes** [comment]
Can you recreate the issue using [JSBin](https://jsbin.com) or provide a link to your live project?

**Comment by skube** [comment]
It's hard to recreate, but I found that in my case the content was inside some other divs with `overflow: hidden` and `overflow-y: scroll` set. Commenting out these two lines got ScrollReveal working!

I tried to recreate the scenario in a [Codepen](https://codepen.io/skube/pen/XgBqpK) but I couldn't recreate the issue. 🤔

**Comment by jlmakes** [comment]
Okay so...

So by default, ScrollReveal attaches `scroll` and `resize` events on the `window`—which essentially expects the document `<body>` to scroll/resize. If you’re using another element as a scrolling container, you must assign that element to `options.container` so ScrollReveal knows the correct element to bind event listeners to.

_Example:_

Here we’re using a fixed-height `<div>` with scroll overflow as our container element... this could be a sidebar, or some widget on the page that scrolls separately from the body.

```html
<div id="container" style="height: 400px; overflow-y: scroll">
    <div class="items"></div>
    <div class="items"></div>
    <div class="items"></div>
</div>
```

So we must tell ScrollReveal about this element, since we’re not the window's scrollbar.

```js
window.sr = ScrollReveal();
sr.reveal('.items', { container: '#container' });
```

Hopefully this helps!
