### ISSUE TITLE
Linting errors

### ISSUE THREAD

**Issue by skube** [jlmakes/scrollreveal#362]
I get the following linting errors when trying to implement ScrollReveal: 

```
[eslint] A function with a name starting with an uppercase letter should only be used as a constructor. (new-cap)
[eslint] "sr" is not defined. (no-undef)
```

I'm adding to my project as:
```js
window.sr = ScrollReveal();
sr.reveal('.mycontent');
```
Am I implementing this incorrectly?

**Comment by jlmakes** [comment]
### ScrollReveal 3.3.6

> A function with a name starting with an uppercase letter should only be used as a constructor.

ESLint is complaining here because you are not using the `new` keyword, which is commonly used with capitalized (constructor) functions.

There is no functional difference between `new ScrollReveal()` and `ScrollReveal()`, but because ScrollReveal is not a traditional constructor (multiple instances are not supported), I often omit the `new` keyword from example code.

In short, you can use either one...

```js
window.sr = ScrollReveal();
sr.reveal('.mycontent');
```

```js
window.sr = new ScrollReveal();
sr.reveal('.mycontent');
```

Moving on...

> `sr`is not defined.

ESLint doesn’t understand that properties on the `window` object are effectively global variables, so in your file’s local scope `sr` technically is undefined.

You can either add `sr` to your ESLint config as a [global variable](http://eslint.org/docs/2.0.0/user-guide/configuring#specifying-globals), or replace your instantiation with something like this:

```js
const sr = window.sr = new ScrollReveal();
sr.reveal('.mycontent');
```

This creates a local variable you can use that silences ESLint.

### ScrollReveal 4 and beyond...

You mentioned you’re using version 3 in a previous issue, but I wanted to mention some differences with ScrollReveal 4 (in late stage beta)—most importantly, **it returns a singleton**.

_Example:_

```js
const A = ScrollReveal()
const B = ScrollReveal()

A === B // true
```

**This means you don’t need to create a global variable.**

So while it’s up to you how to handle the first ESLint warning concerning the `new` keyword, the second warning where `sr` is undefined can be avoided entirely by just leveraging the singleton like this:

```js
ScrollReveal().reveal('.mycontent');
```
