### ISSUE TITLE
Multiple Elements

### ISSUE THREAD

**Issue by discoveryjames** [jlmakes/scrollreveal#367]
What version are you running on the demo website?

If you use a interval reveal using the version on the github, it continues to reveal all regardless of whether they are visible or not, whereas if you use the version on your demo website it works as expected (interval reveals as they become visible).

Great library by the way!

**Comment by jlmakes** [comment]
Every ScrollReveal instance has a `version` property, so can always determine what version is in use by entering this into the console:

```js
ScrollReveal().version
```

The demo is running **4.0.0-beta.2**.

> "If you use a interval reveal using the version on the github, it continues to reveal all regardless of whether they are visible or not..."

This is a known limitation of the v3.x sequencer, and one of the main feature improvements made in [version 4](https://github.com/jlmakes/scrollreveal/pull/323). Getting it to "work as expected" has been surprisingly difficult, but it’s very close!

**Comment by discoveryjames** [comment]
Ahh, thanks for the quick response!

Yeah, it's very close. The only issues I found are that if you refresh the page already scrolled or scroll too quick it doesn't reveal the elements. Other than that it seems to work very well!

**Comment by jlmakes** [comment]
"Scrolling too fast" has been [solved since I beta 4](http://jsbin.com/totumop/2/edit?html,css,output) (#341), but there’s still a bug when using `options.reset` preventing me from dropping the beta tag.

**Comment by jlmakes** [comment]
Alright so now is the time @discoveryjames, the new sequencer in `v4.0.0-beta.10` is the best one yet. (I can’t break it.) Give it a whirl!

`npm i scrollreveal@beta` or `https://unpkg.com/scrollreveal@beta`

**Comment by discoveryjames** [comment]
@jlmakes thanks for letting me know!

I've just compared the two versions, an issue seems to prevent elements revealing in quite a few different scenarios, which worked fine on the previous version.

Would it be useful for you if I setup a demo of our website with beta 9 and beta 10, to that you can see?

**Comment by jlmakes** [comment]
I knew I wasn’t finished, but I was hoping it’d hold up a bit better than this... I too have found issues with the `beta.10` sequencer. (This is what I get for deciding to release at 5am instead of going to bed.)

Luckily, a lot of other stuff I was working on in `beta.10` does appear to be functioning well—so again, it comes down to sequencer logic being a real pain in the arse.

I appreciate the offer @discoveryjames, but your willingness to help me test is more than enough. Just give me another day or two to patch up the sequencer for `beta.11`.

**Comment by discoveryjames** [comment]
@jlmakes sounds good, let me know and I'll test it for you!

**Comment by jlmakes** [comment]
Alright, `beta.11` is out @discoveryjames, which should score well across the board. There’s actually one edge case I want to address (that I won’t mention, teehee), so think there‘s a `beta.12` coming before I drop the beta tag.

Let me know what you find.

**Comment by discoveryjames** [comment]
I still seem to get similar issues. I'll have a mess about later see if I can find anything which is causing the issues, but a few elements fail to reveal.

I have reverted back to beta.9 for now, which seems to resolve the issues. I'll try and work it out and give you the heads up!

**Comment by jlmakes** [comment]
The `beta.9` sequencer was very close—but if you scroll a sequence completely out of view, and back again and it will skip an element. The "off by 1" issues were so difficult to avoid, I concluded it was a flawed solution.

In `beta.10`, a new sequencer was developed but I left a hole in the conditional logic—which actually threw errors when a sequence was completely out of view.

The reason all these issues stem from sequences being out of view, is because `options.reset` is very popular and needs to work sequenced elements.

I haven’t broken `beta.11` yet though, so I‘m curious where it’s failing (and with what errors). Please help me recreate some problems!

**Comment by discoveryjames** [comment]
@jlmakes I have completed some testing on beta.14 this morning, and it seems to be the best yet! Going to try it on a larger screen later, as I have previously been testing on that.

Seems to be just about there though!
