### ISSUE TITLE
Layout slides and doesn't snap to the browser window with side animations

### ISSUE THREAD

**Issue by ZCweb** [jlmakes/scrollreveal#369]
The version of ScrollReveal I think is 3.3.4. I use this library on most of my sites. On websites everything should be contained in the browser. I noticed that if I enable scrollreveal animations then on iOS devices and Safari that the window scrolls left to right.  It is almost as if the animations that are moving in from the sides are pushing out the container of the website.  After I go past the animations then everything snaps back into place. This causes the browser to think that there is more outside of the main container. Maybe there is a easy fix with CSS. Or something else.

**Comment by ZCweb** [comment]
The version of ScrollReveal I think is 3.3.4. I use this library on most of my sites. On websites everything should be contained in the browser. I noticed that if I enable scrollreveal animations then on iOS devices and Safari that the window scrolls left to right.  It is almost as if the animations that are moving in from the sides are pushing out the container of the website.  After I go past the animations then everything snaps back into place. This causes the browser to think that there is more outside of the main container. Maybe there is a easy fix with CSS. Or something else.

One website with the issue is here
https://www.tarponfish.com/

**Comment by jlmakes** [comment]
Have you tried using `overflow-x: hidden` on your `<body>`?
(It’s helpful when using ScrollReveal, on any device.)

**Comment by ZCweb** [comment]
You're right I had it on the body tag. That was added by a push slider which I think set the `body` also as `position:relative` and `left:0` which may have been the cause. What I did also was put the `overflow-x: hidden` on one of the wrapping div classes and it worked. I have all sections in that wrapping div. Thank you.

**Comment by ZCweb** [comment]
This added another problem for me as it now has added a scrollbar to some of the divs with the `over-flow-x: hidden`. If you go to https://www.tarponfish.com/ and scroll down to the 'call to action' you'll see a scrollbar added to it. I set `height:auto` and it didn't  remove the scroll. The scroll is gone once I go past the section or maybe when the animations are done. Would you know some CSS to solve this issue or maybe what is going on.

**Comment by jlmakes** [comment]
When you use ScrollReveal to slide something in from the right for example, it actually changes the position of that element (and the size of its container).

![18f76420-5995-11e4-9f4e-0a22eb7581cd](https://user-images.githubusercontent.com/2044842/29272606-100b3120-8101-11e7-95d3-55c4ee43923a.png)

This is content overflow—this is normal browser behavior, and it creates scrollbars.

If you’re getting unwanted scrollbars horizontally or vertically, it's because you are using ScrollReveal to create animations that create content overflow.

It sounds like `overflow-x: hidden` solved one part of the problem, but if you’re still using animations that travel vertically, you may need an `overflow-y: hidden` on a wrapping div class as well.

**Comment by ZCweb** [comment]
Thank you that worked. Some of the sections were having animations come from the bottom and those would need the `overflow:y`.

**Comment by stevenjoezhang** [comment]
Thanks, I have a similar issue, and adding `overflow-x: hidden;` to `<html>` (not `<body>`) works!
