### ISSUE TITLE
Problems loading dynamically sized images

### ISSUE THREAD

**Issue by geonanorch** [jlmakes/scrollreveal#404]
I am using scrollreveal with a single 'trigger' element positioned at the end of a container displaying thumbnails. Everytime the trigger is revealed, more thumbnails are fetched asynchronously and added to the container.

This is what the code looks like:

```js
    <div class="container">
      <span class="thumbs"></span>
      <span class="trigger"></span>
    </div>
```

and

```js
  $(document).ready(function() {
    var stockScrollreveal = ScrollReveal({
      origin: 'right',
      distance: '20px',
      opacity: 1,
      scale: 0.9,
      mobile: true,
      reset: true,  // true causes random bug, false works fine
      useDelay: 'always',
      viewFactor: 0.01,
    });
    $('.container').each(function() {
      stockScrollreveal('.trigger', {
        container: this,
        afterReveal: stockFetchMore,
      });
    });
  }
```

and

```js
function stockFetchMore(el) {
  lib.stock.fetch()
    .then(items => $('.thumbs').append(items.reduce((html, item) => html + `<img src="${item.thumb}"/>', '')))
    .then(() => stockScrollreveal.sync());
}
```

This works fine if the `reset` option is unset. When is it set however, the `afterReveal` callback is randomly not invoked (say after 5-10 scrolls/iterations, but not always at the same place --although the data returned is the same in each test). I also saw that the `afterReveal` and `afterReset` callbacks are not always invoked in the same sequence.

I also tried to introduce a delay before calling `sync()`, no luck.

I tested this with Firefox 54.0.1 and scrollreveal v3.3.6 and v4.0.0.beta-24, so it is not a new bug.

**Comment by jlmakes** [comment]
I appreciate the example code, but would you mind putting together a working demo?

**Comment by geonanorch** [comment]
Ok, working on it. I have a working standalone page, struggling to reproduce in that case. I have to figure out what the difference is with my original code.

**Comment by jlmakes** [comment]
This code you shared looks odd:

```js
stockScrollreveal('.trigger', {
    container: this,
    afterReveal: stockFetchMore,
});
```

I would expect:

```diff
- stockScrollreveal('.trigger', {
+ stockScrollreveal.reveal('.trigger', {
     container: this,
     afterReveal: stockFetchMore,
 });
```

**Comment by geonanorch** [comment]
Well, 2h30 burnt and still no luck. I had the bug in my original code with the exact sequence of images included in this [jsbin](http://jsbin.com/geyayuh/edit?html,output) upon displaying the third page of 10 images but cannot reproduce in jsbin (I still experience the bug in my original code, but not always at the end of the same page, so almost certainly timing-related).

One (important?) thing I noticed: after the bug occurred (sometimes on page 3, sometimes 4, or 23!), I still get the visual effect on the revealed trigger, but `afterReveal()` is no longer called. I can resume the paging by scrolling up and then down again, but sometimes only after multiple up-downs --drives me nuts.

Maybe that is enough to point you in the right direction. I will try to give it another go later...

And yes sorry, the code in the description is incorrect: I just typed it based on my original code but did not run it.

**Comment by jlmakes** [comment]
Thanks for the effort though @geonanorch , I appreciate the JSBin. I’ll take a look through your example, and see if anything jumps out at me.

**Comment by jlmakes** [comment]
I think this is (at least in part) a race condition.

The first clue is that this feature involves asynchronously loading content. The second clue is something I've encountered in the past: images change size while loading unless you explicitly set their dimensions. _I think this is the root of your problem._

Here's the important bit of my [Live Demonstration (Broken)](https://jsbin.com/somunat/1/edit?html,output)

```js
const urls = [...]

const fragment = src => `
  <span>
    <a href="#!"><img src="${src}"></a>
  </span>`

const defaults = {
  origin: 'right',
  distance: '20px',
  duration: 500,
  opacity: 1,
  scale: 0.9,
  mobile: true,
  reset: true,
  useDelay: 'always',
  viewFactor: 0.01
}

$(document).ready(function() {
  $('.container').each(function() {
    const $trigger = $('.trigger', this)

    ScrollReveal(defaults).reveal($trigger[0], {
      container: this,
      afterReveal: () => {
        const page = Number($trigger.attr('page'))

        let html = ''
        for (let i = 0; i < 10; i++) {
          const src = urls[(page * 10 + i) % urls.length]
          html += fragment(src)
        }

        $('.items', this).append(html)
        $trigger.attr('page', page + 1)
        $trigger.text(page + 1)
      }
    })
  })
})
```

_Some changes..._

* I removed a couple `setTimeouts`
* I removed `ScrollReveal().sync()`
* I'm using ScrollReveal 4 to streamline how you're invoking ScrollReveal

It seems I was able to reproduce the problem better this way, and I managed to take a look at the broken state.

![screen shot 2017-12-20 at 2 01 07 pm](https://user-images.githubusercontent.com/2044842/34210812-6d11bc18-e597-11e7-8377-acfdd5a5d265.png)

![screen shot 2017-12-20 at 2 04 58 pm](https://user-images.githubusercontent.com/2044842/34208488-d3e99d56-e58e-11e7-85ea-91d228b892b9.png)

The odd bit is `visible: false`, because it clearly is visible within its container. So I took a look at the container, and...

![screen shot 2017-12-20 at 2 44 27 pm](https://user-images.githubusercontent.com/2044842/34210835-7c98e5c6-e597-11e7-98fc-2b246988ee6a.png)

**Look at those dimensions! The container `bounds` haven't been updated!**

This appears to be why you were having some success using `ScrollReveal().sync()`, because it invokes the main event handler [`ScrollReveal().delegate()`](https://github.com/jlmakes/scrollreveal/blob/development/src/instance/functions/delegate.js) with an empty event, which is how ScrollReveal caches container geometry.

Running with these observations and race condition theory, you must:

* Use fixed sizes for your images
* Invoke the delegate manually

```diff
 const urls = [...]

 const fragment = src => `
   <span>
-    <a href="#!"><img src="${src}"></a>
+    <a href="#!"><img src="${src}" width="200px" height="200px"></a>
   </span>`

 const defaults = {
   origin: 'right',
   distance: '20px',
   duration: 500,
   opacity: 1,
   scale: 0.9,
   mobile: true,
   reset: true,
   useDelay: 'always',
   viewFactor: 0.01
 }

 $(document).ready(function() {
   $('.container').each(function() {
     const $trigger = $('.trigger', this)

     ScrollReveal(defaults).reveal($trigger[0], {
       container: this,
       afterReveal: () => {
         const page = Number($trigger.attr('page'))

         let html = ''
         for (let i = 0; i < 10; i++) {
           const src = urls[(page * 10 + i) % urls.length]
           html += fragment(src)
         }

         $('.items', this).append(html)
         $trigger.attr('page', page + 1)
         $trigger.text(page + 1)
+        ScrollReveal().delegate()
       }
     })
   })
 })
```

Here's a [Live Demonstration (Working)](https://jsbin.com/somunat/2/edit?html,output)

**Comment by jlmakes** [comment]
_Thought I'd add a note here since the ScrollReveal 4 documentation isn't ready yet._

When you invoke `sync()`, yes ScrollReveal re-captures new elements added to the DOM (by re-running all past reveals), but it also re-runs the initialization... which includes calling the primary event handler `delegate()`.

For situations like the one we're in (and to be able to unbind event listeners), the `delegate()` method was made into a bound public instance property for ScrollReveal 4.

So your idea to use `sync()` was definitely on the money, but the impact was coming from the internal `delegate()` call—so that's why we just invoke it directly.

**Comment by jlmakes** [comment]
_Thought I'd add a note here since the ScrollReveal 4 documentation isn't ready yet._

When you invoke `sync()`, yes ScrollReveal re-captures new elements added to the DOM (by re-running all past reveals), but it also re-runs the initialization... which includes calling the event handler `delegate()` once.

For situations like the one we're in (and to be able to unbind event listeners), the `delegate()` method was made into a bound public instance property for ScrollReveal 4.

So your idea to use `sync()` was definitely on the money, but the impact was coming from the internal `delegate()` call—so that's why here we just invoke it directly.

**Comment by jlmakes** [comment]
_Thought I'd also add a note here since the ScrollReveal 4 documentation isn't ready yet._

When you invoke `sync()`, yes ScrollReveal re-captures new elements added to the DOM (by re-running all past reveals), but it also re-runs the initialization... which includes calling the event handler `delegate()` once.

However, the `delegate()` method was made into a bound public instance property for ScrollReveal 4.

So your idea to use `sync()` was definitely on the money, but the impact was coming from the internal `delegate()` call—so that's why here we just invoke it directly.

**Comment by geonanorch** [comment]
Wow, that is some analysis ;-)    Thank you very much. I was going to object about fixed-size images, but you also covered that in part 2!
I will integrate your answer then close the issue (might be beginning of next year). Maybe worth a warning in the documentation around `sync()` ?

And compliment on your open/closed issue ratio, combined with such thorough answers they are truly outstanding.

**Comment by jlmakes** [comment]
Thanks a lot @geonanorch, I typically enjoy helping others with their issues, it makes the community and product better. I also really appreciate that you took the time to reproduce the issue, makes me feel a lot better about spending my time.

I updated **Part 2** to show a working example using dynamically sized images.

> ...maybe it’s worth adding a warning to the documentation around `sync()` ?

The new ScrollReveal 4 documentation is going to include a few guides, and tons of API reference; there's one article on loading asynchronous content and using `sync()`, but I may indeed write a follow-up about dynamically sized containers and `delegate()`.

It's also worth noting, there may be an opportunity here to automate calling `delegate()` with dynamically sized containers, perhaps using [`MutationObserver`](https://developers.google.com/web/updates/2012/02/Detect-DOM-changes-with-Mutation-Observers). I may open that as a feature request for 4.1.

**Comment by jlmakes** [comment]
It's also worth noting, there may be an opportunity here to automate calling `delegate()` with dynamically sized containers, perhaps using [`MutationObserver`](https://developers.google.com/web/updates/2012/02/Detect-DOM-changes-with-Mutation-Observers)... I may open that as a feature request in the future.
