### ISSUE TITLE
Undefined order when staggering

### ISSUE THREAD

**Issue by bakura10** [jlmakes/scrollreveal#408]
Hi :),

I'm using ScrollReveal v4 beta 24 and I've found out that depending on my scrolling speed, the reveal order does not respect the DOM order but seems... random.

It's a bit hard to explain so here is a short video I've capture: https://www.dropbox.com/s/jqkjozs3jdy3mqd/video.mov?dl=0

As you can see once scrolling to the second row, the three attempts at scrolling at different speed leaded to three different results, which does not seem consistent.

Here is the code I've used:

```js
const options = {
    duration: 500,
    distance: '45px',
    easing: 'ease-in-out'
}

ScrollReveal.reveal('[data-animation-type="fade-in"]', options, 150);
```

Is this a known issue of version 4? Thanks!

**Comment by jlmakes** [comment]
Thanks for the video, Michaël.

I understand what's happening, but would you mind helping me out by creating a simple demonstration of this problem using something like [JSBin](http://jsbin.com)?

I ask because it facilitates access to ScrollReveal's state at the time of error, and prove there are no external conflicts at play.

**Comment by bakura10** [comment]
Hi @jlmakes , yes I can try to do that.

However in the meantime, I'll give you an access to the in development website: https://diamant-development.myshopify.com

Enter the password _rewblo_ then navigate to this page: https://diamant-development.myshopify.com/blogs/news

Apparently the wrong order happens when I scroll very slowly to have only a few pixels visible of the next line.

If it can helps, I'm using LazySizes.

I will try to set up a minimal JSBin today !

**Comment by bakura10** [comment]
I've been able to reproduce this in JSBin. Please find it here: https://jsbin.com/raxocujuyo/edit?html,output

Make sure to extend the window to have 3 items per row, then scroll very slowly until the second row with 3 items appear and you will see the order is undefined :p.

**Comment by jlmakes** [comment]
Okay, thank you for the extra information.

**The behavior is the result of your use of `options.viewFactor = 0.15`**

That option means that 15% of an element must be within its container before it is considered visible by ScrollReveal. In other words, shorter elements will reveal first; if you look carefully, the element that's revealing "in the wrong order" is actually the shortest of the 3 on its row.

This isn't the case when scrolling fast, because the 2nd row of elements are triggered before the 1st row is done animating—and the sequencer just keeps revealing until the last visible element.
