### ISSUE TITLE
Scrollreveal.js blinks on mobile safari

### ISSUE THREAD

**Issue by strin** [jlmakes/scrollreveal#411]
Just go to https://scrollrevealjs.org on iPhone safari. The divs would appear fully first, and then again start with `opacity: 0` and transition to `opacity: 1`. This creates an annoying blinking effect.

**Comment by jlmakes** [comment]
This isn't a bug, and is known behavior, unfortunately.

This "flickering" is because the DOM begins rendering before the JavaScript is evaluated... so there's a brief moment before ScrollReveal hides the elements.

I'm actively working on testing and improving a recommend practice here, but it's actually surprisingly hard behavior to recreate; using a sandbox (such as [JSBin](http://jsbin)), disabling the cache and throttling my internet connection hasn't been enough.

The basic idea is to use `visibility: hidden` manually on your elements, and let ScrollReveal reveal them—but the catch is that this should only be done when JavaScript and ScrollReveal are supported/enabled.

**Comment by KonstantinKudelko** [comment]
Hey @jlmakes 

Thanks for this awesome library 🔥
Not ScrollReveal has 4.0.7 version, do you have some solution regarding this issue?

Thanks one more time 🙏

**Comment by jlmakes** [comment]
@KonstantinKudelko Maybe https://scrollrevealjs.org/guide/user-experience.html can help you?
