### ISSUE TITLE
Google Map overflows container on reveal

### ISSUE THREAD

**Issue by claudemuller** [jlmakes/scrollreveal#412]
Hi there

Thanks for the project - really nice work.

I'm trying to scroll-reveal a Google Map. While the scrolling works, when loaded, the map overflows the explicit bounds set by the height attribute on the containing element as well as in CSS. There are issues with Gmaps when the container is given a height after loading that it wouldn't render correctly. The fix for that seems to be to call the .resize() method on the map, but I've tried that in afterReveal() to no avail. I've tried a CSS height, explicit height, showing and hiding before and after the reveal and a few random CSS things. I'm not sure what else to try. Any ideas?

OS: Windows 10 SL
Browser: Google Chrome 63.0.3239.132
ScrollReveal: 3.3.6

I've set up a fiddle here - http://jsfiddle.net/5vk8fr0c/1/ The map is only suppose to be 200px high, but as you can see it overflows. Remember to scroll down to reveal the map :)

Thanks for your help :)

**Comment by jlmakes** [comment]
Google Maps adds `position: relative; overflow: hidden` to the target element. For whatever reason, that is being lost during integration. Rather than debug why, I decided to try ScrollReveal 4 and it works as expected.

The new documentation is holding up the release, but v4 is just better software (don't let the `beta` tag throw you, all work from the last year has gone into it).

Please see [what's new in 4.0](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) and upgrade your project to the [latest version](https://unpkg.com/scrollreveal@beta).

**Comment by claudemuller** [comment]
Oh I see. Well I tried v4 but the problem was still occurring. But then I thought let me try explicitly setting position (which I did before) and overflow (the secret) in my CSS and that did it! 

I'll keep using v4 beta for dev but do you know when it'll be officially released as I'm using the npm version and need to distribute this to users so they need a stable package.json to install.

Thanks for your help @jlmakes, saved my bacon :)

**Comment by jlmakes** [comment]
Aha, that is the six million dollar question.

It's the [new documentation](https://user-images.githubusercontent.com/2044842/35185169-396f44ee-fe00-11e7-808d-58884832f847.png) that has been taking me ☠️  **forever** ☠️ because my perfectionism is running rampant. I've got 35 pages of guides and reference material, and I just finished up a month-long detour developing a custom scrollbar solution (because dark UIs look terrible on platforms without it).

It's almost ready, I just need a few really productive days.

**Comment by jlmakes** [comment]
Aha, that is the six million dollar question.

It's the [new documentation](https://user-images.githubusercontent.com/2044842/35186731-34cb1184-fe19-11e7-84f7-c8067668b966.png) that has been taking me ☠️  **forever** ☠️ because my perfectionism is running rampant. I've got 35 pages of guides and reference material, and I'm happy with the progress. It's almost ready, I just need a few really productive days.

**Comment by claudemuller** [comment]
No worries, good luck :)
