### ISSUE TITLE
Bug with distance and position absolute

### ISSUE THREAD

**Issue by cgahmann** [jlmakes/scrollreveal#419]
Hi,

With the latest ScrollReveal 4 and `distance: '20px'` on the parent element,  and `position: absolute` on the child element, the positioning disappears?

It works without the `option.distance`.

Demo: http://jsbin.com/zadaxutako/edit?html,css,js,output

This does not work on:

- Firefox 58.02 on macOS 10.11
- Chrome 64.0.3282.186 on macOS Sierra 10.11

**Comment by jlmakes** [comment]
Thanks for the reproduction @cgahmann, I really appreciate it.

I've also noticed that on Safari, it appears to load correctly but exhibits the same broken layout on resize. I'll take a closer look!

**Comment by cgahmann** [comment]
No problem :) I have the same problem with the latest ScrollReveal 3.

**Comment by jlmakes** [comment]
This looks like a browser bug, or just unexpected CSS behavior.

The way you've constructed the DOM, and the CSS you've used, has exposed the issue—when a CSS transform is present on the `.row`, your layout does not do as you intend.

Demo: http://jsbin.com/lotozubaso/edit?css,output

```css
.row {
  max-width: 50%;
  /* transform: scale(1); */
}
```

Just toggle the CSS transform on/off to see what I mean. I'm not sure what browser bug/behavior this is, but it's not caused by ScrollReveal.

The reason `options.duration` appears to cause the bug, is because when used, it creates a CSS transform—but when omitted, ScrollReveal only animates opacity. This "generate only whats needed" approach to styles is new to ScrollReveal 4, so version 3 will always surface this odd browser behavior, regardless of configuration.

**Comment by cgahmann** [comment]
Thanks! Yes, it's a unexpected CSS behavior: https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children

**Comment by jlmakes** [comment]
Luckily, HTML/CSS can be combined in all kinds of ways, there's surely a way to create the layout you want that doesn't expose this bug. Good luck!

Thanks again for creating a reproduction of the issue, it really helps me offer support.
