### ISSUE TITLE
Interval time

### ISSUE THREAD

**Issue by Hazlank** [jlmakes/scrollreveal#434]
Hi,all
I set interval time with element collection，but sometime i don't know why some elements will not appear and wait for a period of time they will appear and go on to do animation. I don't know how to reappear this bug.
- scrollreveal 3.4.0

**Comment by jlmakes** [comment]
Hey Hazlank,

You're not the first person the v3.x sequencer has confused with its behavior.

Sequenced elements are treated as a group: if any of them are visible, the entire sequence is considered visible. This means it's possible (with enough elements) to scroll faster than the sequence, and be stuck waiting for in-view elements to reveal. (I think this is what you're describing.)

This is not ideal, but the sequencer has been really tough to get right! In fact, this is what I have invested much of my time into for improving ScrollReveal 4.

In a few days, you will have the option to upgrade to v4.x which you should find behaves far more intuitively. Otherwise, you can explore the other people who brought up similar issues with the v3.x sequencer: #367 #358 #342 #339 #305
