### ISSUE TITLE
In AND out

### ISSUE THREAD

**Issue by mikaelcedergren** [jlmakes/scrollreveal#439]
How do I just let it animate as it goes in and out of viewport? Right now I got this:

```js
window.sr = ScrollReveal();
sr.reveal('.animate-in', { duration: 1000 }, 100);

**Comment by jlmakes** [comment]
Have you tried the reset option? e.g:

```js
sr.reveal('.animate-in', { duration: 1000, reset: true }, 100);
```

**Comment by jlmakes** [comment]
Also, if you're using ScrollReveal v3.x, sequenced elements reveal as a group (instead of their individual visibility). It's possible this is what you're experiencing.

If you're willing to upgrade, [ScrollReveal 4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) has a much better sequencer. e.g:

```js
ScrollReveal().reveal('.animate-in', { duration: 1000, interval: 100 });
```

Official launch and docs coming very soon!

**Comment by jlmakes** [comment]
Also I noticed you're using v3.x, which reveals sequenced elements as a group. It's possible this is what you're experiencing. If you're willing to upgrade, [ScrollReveal 4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) has a much better sequencer. e.g:

```js
ScrollReveal().reveal('.animate-in', { duration: 1000, interval: 100 });
```
