### ISSUE TITLE
Bug with full page.js + scroll reveal.js

### ISSUE THREAD

**Issue by basile121** [jlmakes/scrollreveal#45]
Hello,
you're plugin is just awesome! But i have a problem when i use the plugin with "full page.js" by alvarotrigo. In fact, you're plugin doesn't work when i add fullpage.js to my website page. Have you got a solution? thank you a lot

**Comment by alvarotrigo** [comment]
@basile121 you can use it together with fullPage.js if you initialize it in the `afterRender` callback and if you make use of the `scrollBar:true` option or otherwise use the `autoScrolling:false`.

From the [fullPage.js FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#parallax-doesnt-work-with-fullpagejs):

>  fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by julianlloyd** [comment]
Thanks for this @alvarotrigo !
